package com.example;

import lombok.Data;
import java.time.LocalDate;

/**
 * Student model class representing a student entity.
 * This is the Model in the MVVM pattern.
 * Using Lombok annotations to reduce boilerplate code:
 * - @Data generates getters, setters, equals(), hashCode(), toString()
 * 
 * Note: Due to annotation processing compatibility issues, we explicitly
 * define constructors that would normally be generated by @NoArgsConstructor
 * and @AllArgsConstructor.
 */
@Data
public class Student {
    private String firstName;
    private String lastName;
    private String email;
    private LocalDate birthDate;

    // The @AllArgsConstructor from Lombok generates this:
    // public Student(String firstName, String lastName) { ... }
    // Since annotation processing isn't working, we add it manually:
    
    /**
     * Default no-argument constructor (generated by @NoArgsConstructor).
     */
    public Student() {
        this("", "", "", null);
    }
    
    /**
     * Constructor with all fields (generated by @AllArgsConstructor).
     */
    public Student(String firstName, String lastName, String email, LocalDate birthDate) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.birthDate = birthDate;
    }    /**
     * Returns the full name by combining first and last name.
     */
    public String getFullName() {
        if (firstName == null) firstName = "";
        if (lastName == null) lastName = "";
        return (firstName + " " + lastName).trim();
    }

    @Override
    public String toString() {
        return getFullName();
    }
    
    // The following methods are generated by Lombok @Data annotation:
    // - getter/setter for firstName
    // - getter/setter for lastName
    // - equals()
    // - hashCode()
    // - toString() (overridden above)
    
    public String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    /**
     * Gets the email address of the student.
     */
    public String getEmail() {
        return email;
    }
    
    /**
     * Sets the email address of the student.
     */
    public void setEmail(String email) {
        this.email = email;
    }
    
    /**
     * Gets the birth date of the student.
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }
    
    /**
     * Sets the birth date of the student.
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        Student student = (Student) obj;
        return (firstName == null ? student.firstName == null : firstName.equals(student.firstName)) &&
               (lastName == null ? student.lastName == null : lastName.equals(student.lastName)) &&
               (email == null ? student.email == null : email.equals(student.email)) &&
               (birthDate == null ? student.birthDate == null : birthDate.equals(student.birthDate));
    }

    @Override
    public int hashCode() {
        int result = firstName != null ? firstName.hashCode() : 0;
        result = 31 * result + (lastName != null ? lastName.hashCode() : 0);
        result = 31 * result + (email != null ? email.hashCode() : 0);
        result = 31 * result + (birthDate != null ? birthDate.hashCode() : 0);
        return result;
    }
}
